### ISSUE TITLE
API doesn't return 2019S course info.

### ISSUE THREAD

**Issue by bchung00** [qstevens/UBC-Courses-API#2]
After testing on the listed three endpoints, it seems that course info for the 2019 summer term is not correctly returned and instead 2018W is. 
https://ubc-courses-api.herokuapp.com/2019S/MATH/200/
https://ubc-courses-api.herokuapp.com/2019S/MATH/220/
https://ubc-courses-api.herokuapp.com/2019S/CPSC/210/

**Comment by qstevens** [comment]
Thanks for bringing this up! I see the error is in the link that I am using to direct subsequent scraping operations. I will make a quick edit, re-scrape the page, and upload the new data onto the database by tonight.
