### ISSUE TITLE
API doesn't return correct seat information and correct status information

### ISSUE THREAD

**Issue by borislavgrigorov** [qstevens/UBC-Courses-API#3]
Fields totalRemaining, currentlyRegistered, generalRemaining, restrictedRemaining and status return incorrect information

**Comment by qstevens** [comment]
Hi Borislav,

I will work on having the scraper run on a schedule, updating to MongoDB.

**Comment by qstevens** [comment]
Hi Borislav,

The fields totalRemaining, currentlyRegistered, generalRemaining, restrictedRemaining and status should return updated information when query the authoritative section endpoints. The fix is more of a bandaid for now because I expect to refactor the whole API in the near future.

Please let me know if you need anything else.

**Comment by borislavgrigorov** [comment]
Hi qstevens, thanks for looking into the issue. I checked and status does get updated correctly. However the other fields totalRemaining, currentlyRegistered, generalRemaining, restrictedRemaining do not. They return null instead. Can you look into this when you get the chance?

**Comment by qstevens** [comment]
Hi Borislav,

Can you send me a link to an example where null is returned?

Thanks.

**Comment by borislavgrigorov** [comment]
https://ubc-courses-api.herokuapp.com/2019W/MATH/103/201/

**Comment by qstevens** [comment]
Hi Borislav,

Try it now

**Comment by borislavgrigorov** [comment]
Now I get application error regardless of the course or section.

**Comment by qstevens** [comment]
That's strange... the app crashed but it seems to return the correct results when it is up.

I've restarted it and it seems to work fine for the links above. If you encounter the error again, please let me know which course or section you are querying that returned an error.

**Comment by borislavgrigorov** [comment]
Hi I tried again and it worked for a few minutes and then it seems to have crashed again. 
I used this url: https://ubc-courses-api.herokuapp.com/2019W/MATH/103/201/

**Comment by qstevens** [comment]
Seems to have been an issue with a null value. I've added a null check to address that, but I'll keep monitoring the API today in case it crashes again.

**Comment by borislavgrigorov** [comment]
It seems to work well now. I tried several courses and they worked. There was one section that it didn'g work for: https://ubc-courses-api.herokuapp.com/2019W/MATH/101/213 can you check that one as well? It seems to be specific to that section. By the way I really appreciate your help with this!

**Comment by qstevens** [comment]
Should be working now.

And no problem! Please let me know if you encounter any other issues. Like I mentioned, I should be rewriting this API in the near future and I will keep these issues in mind when making something more robust.
